"""
Final-report step.

Writes the populated .env file into <install_path>/secrets/.env
and a human-readable report.md into <install_path>/logs/.

Now covers Phase 3 (GCP/Vertex), Phase 4 (Gemini), and Phase 5 (OneDrive).
"""

from __future__ import annotations

import logging
from pathlib import Path

from installer.config.schema import Phase3Config
from installer.utils import ui

log = logging.getLogger(__name__)


def emit(cfg: Phase3Config, *, install_path: Path) -> None:
    ui.section("Step 13 -- Final report", "Writing .env and summary.")
    _write_env(cfg, install_path)
    _write_report(cfg, install_path)


# ---------------------------------------------------------------------------
# .env
# ---------------------------------------------------------------------------

def _write_env(cfg: Phase3Config, install_path: Path) -> None:
    path = install_path / "secrets" / ".env"
    path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "# Auto-generated by unified bootstrap (Phase 3+4+5). Do not commit.",
        "",
        "# ── Business ─────────────────────────────────────────────────────",
        f'COMPANY_NAME="{cfg.business.display_name}"',
        f'COMPANY_DOMAIN="{cfg.business.domain}"',
        "",
        "# ── GCP ──────────────────────────────────────────────────────────",
        f'GCP_PROJECT_ID="{cfg.gcp.project_id}"',
        f'GCP_PROJECT_NUMBER="{cfg.gcp.project_number or ""}"',
        f'GCP_REGION="{cfg.gcp.region}"',
        f'GCP_LOCATION="{cfg.gcp.location}"',
        f'GOOGLE_APPLICATION_CREDENTIALS="{cfg.service_account.key_path or ""}"',
        # Explicit project ID for SDK clients that don't read it from the key
        f'GOOGLE_CLOUD_PROJECT="{cfg.gcp.project_id}"',
        "",
        "# ── GCS Buckets ───────────────────────────────────────────────────",
        f'GCS_BUCKET_RAW="{cfg.storage.raw_bucket}"',
        f'GCS_BUCKET_PROCESSED="{cfg.storage.processed_bucket}"',
        f'GCS_BUCKET_ARCHIVE="{cfg.storage.archive_bucket}"',
        "",
        "# ── Vertex AI Search ──────────────────────────────────────────────",
        f'VERTEX_DATA_STORE_ID="{cfg.vertex.data_store_id}"',
        f'VERTEX_ENGINE_ID="{cfg.vertex.engine_id}"',
        f'VERTEX_TIER="{cfg.vertex.tier}"',
        f'VERTEX_CONTENT_CONFIG="{cfg.vertex.content_config}"',
        f'VERTEX_INDUSTRY_VERTICAL="{cfg.vertex.industry_vertical}"',
        f'VERTEX_SERVING_CONFIG="{cfg.serving_config_path()}"',
        "",
        "# ── Phase 4: Gemini AI Chat ───────────────────────────────────────",
        f'PHASE4_ENABLED="{"true" if cfg.gemini.enabled else "false"}"',
        f'GEMINI_API_KEY="{cfg.gemini.api_key}"',
        f'GEMINI_MODEL="{cfg.gemini.model}"',
        "",
    ]

    # ── Gmail ──────────────────────────────────────────────────────────────
    gmail = cfg.connector("gmail")
    if gmail and gmail.enabled:
        opts = gmail.options
        refs = gmail.secret_refs
        lines += [
            "# ── Gmail connector ──────────────────────────────────────────",
            'GMAIL_ENABLED="true"',
            f'GMAIL_OAUTH_CLIENT_ID="{opts.get("client_id", "")}"',
            f'GMAIL_USER_EMAIL="{opts.get("user_email", "")}"',
            f'GMAIL_LABEL_FILTER="{opts.get("label", "INBOX")}"',
            f'GMAIL_QUERY="{opts.get("query", "")}"',
            f'GMAIL_SYNC_SCHEDULE="{gmail.schedule_cron}"',
            f'GMAIL_OAUTH_CLIENT_SECRET_REF="{refs.get("gmail-oauth-client-secret_ref", "")}"',
            f'GMAIL_REFRESH_TOKEN_REF="{refs.get("gmail-refresh-token_ref", "")}"',
            "",
        ]
    else:
        lines += ['GMAIL_ENABLED="false"', ""]

    # ── Google Drive ────────────────────────────────────────────────────────
    gdrive = cfg.connector("gdrive")
    if gdrive and gdrive.enabled:
        opts = gdrive.options
        lines += [
            "# ── Google Drive connector ───────────────────────────────────",
            'GDRIVE_ENABLED="true"',
            f'GDRIVE_MODE="{opts.get("mode", "service_account")}"',
            f'GDRIVE_DRIVE_TYPE="{opts.get("drive_type", "my_drive")}"',
            f'GDRIVE_FOLDER_IDS="{",".join(opts.get("folder_ids", []))}"',
            f'GDRIVE_MIME_ALLOWLIST="{",".join(opts.get("mime_allowlist", []))}"',
            f'GDRIVE_SYNC_SCHEDULE="{gdrive.schedule_cron}"',
            "",
        ]
    else:
        lines += ['GDRIVE_ENABLED="false"', ""]

    # ── OneDrive ────────────────────────────────────────────────────────────
    onedrive = cfg.connector("onedrive")
    if onedrive and onedrive.enabled:
        opts = onedrive.options
        lines += [
            "# ── OneDrive connector (Phase 5) ─────────────────────────────",
            'ONEDRIVE_ENABLED="true"',
            f'AZURE_CLIENT_ID="{opts.get("azure_client_id", "")}"',
            f'AZURE_TENANT_ID="{opts.get("azure_tenant_id", "")}"',
            f'ONEDRIVE_FOLDER_PATH="{opts.get("folder_path", "")}"',
            f'ONEDRIVE_SYNC_SCHEDULE="{onedrive.schedule_cron}"',
            # GCS bucket reused from Phase 3 storage
            f'GCS_BUCKET_NAME="{cfg.storage.raw_bucket}"',
            f'VERTEX_DATASTORE_ID="{cfg.vertex.data_store_id}"',
            f'VERTEX_LOCATION="{cfg.gcp.location}"',
            "",
        ]
    else:
        lines += ['ONEDRIVE_ENABLED="false"', ""]

    lines += [
        'LOG_LEVEL="INFO"',
        'DRY_RUN="false"',
        "",
        "# ── Cron / scheduler helpers ──────────────────────────────────────",
        "# These are re-stated explicitly so scheduled sync jobs (OneDrive,",
        "# GDrive) can source this file and run without any manual env exports.",
        f'SA_KEY_PATH="{cfg.service_account.key_path or ""}"',
        f'GCS_BUCKET_NAME="{cfg.storage.raw_bucket}"',
        f'VERTEX_DATASTORE_ID="{cfg.vertex.data_store_id}"',
        f'VERTEX_LOCATION="{cfg.gcp.location}"',
    ]

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        import os
        os.chmod(path, 0o600)
    except (OSError, NotImplementedError):
        pass
    ui.success(f".env written: {path}")


# ---------------------------------------------------------------------------
# report.md
# ---------------------------------------------------------------------------

def _write_report(cfg: Phase3Config, install_path: Path) -> None:
    path = install_path / "logs" / "last-bootstrap-report.md"
    path.parent.mkdir(parents=True, exist_ok=True)

    gmail    = cfg.connector("gmail")
    gdrive   = cfg.connector("gdrive")
    onedrive = cfg.connector("onedrive")

    gemini_line = (
        f"`{cfg.gemini.model}`  (API key set)"
        if cfg.gemini.enabled else "disabled"
    )

    md = f"""# Bootstrap Report — {cfg.business.display_name}

**Schema version:** {cfg.schema_version}
**Company:** {cfg.business.display_name} ({cfg.business.legal_name})
**Contact:** {cfg.contact.full_name} <{cfg.contact.email}>
**GCP project:** `{cfg.gcp.project_id}` (number: `{cfg.gcp.project_number or "unknown"}`)
**Region:** {cfg.gcp.region}

## Resources created

| Kind | Name / ID |
|---|---|
| Service account | `{cfg.service_account.email}` |
| Raw bucket | `gs://{cfg.storage.raw_bucket}` |
| Processed bucket | `gs://{cfg.storage.processed_bucket}` |
| Archive bucket | `{("gs://" + cfg.storage.archive_bucket) if cfg.storage.archive_bucket else "(none)"}` |
| Data store | `{cfg.vertex.data_store_id}` |
| Engine | `{cfg.vertex.engine_id}` |
| Tier | `{cfg.vertex.tier}` |
| Layout Parser | `{cfg.vertex.enable_layout_parser}` |

**Serving config path:**
```
{cfg.serving_config_path()}
```

## Phase 4 — Gemini chat

- Status: **{"ENABLED" if cfg.gemini.enabled else "disabled"}**
- Model: {gemini_line}
- Landing page: **{"/ bob" if cfg.gemini.enabled and cfg.gemini.phase4_start_page else "/"}**

## Connectors

| Connector | Status |
|---|---|
| Gmail | {"**ENABLED**" if gmail and gmail.enabled else "disabled"} |
| Google Drive | {"**ENABLED**" if gdrive and gdrive.enabled else "disabled"} |
| OneDrive | {"**ENABLED**" if onedrive and onedrive.enabled else "disabled"} |

## Next actions

1. Share Drive folders with `{cfg.service_account.email}` (Viewer role).
2. Run `python -m installer.connectors.gmail authorize` to complete Gmail OAuth.
3. If OneDrive enabled: first sync will prompt Microsoft device-flow login.
4. Run `python -m installer --verify` to sanity-check everything.
"""
    path.write_text(md, encoding="utf-8")
    ui.success(f"Report written: {path}")